// Richy production build. Runs on Vercel (see vercel.json buildCommand) - this
// machine may not have node at all, which is fine: local dev keeps using the
// runtime-Babel preview.html harness, while production serves the precompiled
// bundle this script writes into public/.
//
// The transform below mirrors preview.html's runtime pipeline EXACTLY (strip
// imports, unwrap the default export, JSX -> React.createElement), so the
// production bundle behaves identically to what the dev harness runs - just
// compiled once at deploy time instead of on every visitor's phone.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync } from "fs";
import { transformSync } from "@babel/core";
import presetReact from "@babel/preset-react";

const BUILD_ID = String(Date.now());

// ---- 1. Compile the app ------------------------------------------------------
const src = readFileSync("budget-app.jsx", "utf8");
const code = src
  .replace(/^\s*import[^\n]*\n/gm, "")
  .replace(/export default function App/, "function App");

const compiled = transformSync(code, {
  presets: [[presetReact, {}]],
  babelrc: false,
  configFile: false,
  compact: true,
  comments: false,
}).code;

// Same scope preview.html builds around eval(): the React hooks the source
// imports, plus the lightweight Recharts stand-in that powers the donut chart.
// NOTE: no "use strict" on purpose - eval() runs the app in sloppy mode today,
// and the bundle must not change the code's semantics.
const preamble = `
var RC = (function () {
  function ResponsiveContainer(props) { return React.createElement("div", { style: { width: props.width, height: props.height } }, props.children); }
  function PieChart(props) { return React.createElement("svg", { viewBox: "0 0 100 100", width: "100%", height: "100%" }, props.children); }
  function Pie(props) {
    var data = props.data || [];
    var total = data.reduce(function (s, d) { return s + (d.value || 0); }, 0) || 1;
    var R = 42, r = 24, cx = 50, cy = 50, ang = -90;
    var arcs = data.map(function (d, i) {
      var frac = (d.value || 0) / total, a0 = ang, a1 = ang + frac * 360; ang = a1;
      var rad = function (a) { return (a * Math.PI) / 180; };
      var x0 = cx + R * Math.cos(rad(a0)), y0 = cy + R * Math.sin(rad(a0));
      var x1 = cx + R * Math.cos(rad(a1)), y1 = cy + R * Math.sin(rad(a1));
      var xi1 = cx + r * Math.cos(rad(a1)), yi1 = cy + r * Math.sin(rad(a1));
      var xi0 = cx + r * Math.cos(rad(a0)), yi0 = cy + r * Math.sin(rad(a0));
      var large = frac > 0.5 ? 1 : 0;
      var dd = "M" + x0 + " " + y0 + " A" + R + " " + R + " 0 " + large + " 1 " + x1 + " " + y1 + " L" + xi1 + " " + yi1 + " A" + r + " " + r + " 0 " + large + " 0 " + xi0 + " " + yi0 + " Z";
      var fill = (props.children && props.children[i] && props.children[i].props.fill) || (data[i] && data[i].color) || "#ccc";
      return React.createElement("path", { key: i, d: dd, fill: fill });
    });
    return React.createElement("g", null, arcs);
  }
  function Cell() { return null; }
  return { ResponsiveContainer: ResponsiveContainer, PieChart: PieChart, Pie: Pie, Cell: Cell };
})();
var useState = React.useState, useEffect = React.useEffect, useRef = React.useRef;
var PieChart = RC.PieChart, Pie = RC.Pie, Cell = RC.Cell, ResponsiveContainer = RC.ResponsiveContainer;
`;

const bundle =
  "/* Richy production bundle - generated by build.mjs, build " + BUILD_ID + ". Do not edit. */\n" +
  "(function () {\n" + preamble + "\n" + compiled +
  "\n;window.RichyApp = App;" +
  "\nwindow.RichyErrorBoundary = (typeof ErrorBoundary !== \"undefined\") ? ErrorBoundary : null;" +
  "\nwindow.RichyBuild = \"" + BUILD_ID + "\";\n})();\n";

// ---- 2. Assemble the public/ output directory --------------------------------
mkdirSync("public/dist", { recursive: true });
writeFileSync("public/dist/app.js", bundle);

// Static files served as-is. preview.html and budget-app.jsx are intentionally
// NOT shipped - they are the dev harness and raw source.
const staticFiles = [
  "icon-180.png",
  "icon-512.png",
  "manifest.webmanifest",
  "firebase-init.js",
  "terms.html",
  "privacy.html",
  "landing.html",
];
for (const f of staticFiles) copyFileSync(f, "public/" + f);

// Script-specific serif fallbacks remain self-hosted so localized titles keep
// their editorial voice offline. License notices travel with the OFL files.
mkdirSync("public/fonts", { recursive: true });
for (const f of readdirSync("fonts")) {
  copyFileSync("fonts/" + f, "public/fonts/" + f);
}

// Badge art: one SVG per badge per appearance (see badges/README.md). Copied
// wholesale rather than listed file by file, so adding art is a drag-and-drop
// into the folder and never an edit to this script.
for (const appearance of ["light", "dark"]) {
  const dir = "badges/" + appearance;
  if (!existsSync(dir)) continue;
  mkdirSync("public/" + dir, { recursive: true });
  for (const f of readdirSync(dir)) {
    if (/\.svg$/i.test(f)) copyFileSync(dir + "/" + f, "public/" + dir + "/" + f);
  }
}

// ---- 3. Vendor the browser runtime ------------------------------------------
// React and Firebase used to be <script src="https://unpkg.com/..."> tags.
// That made every cold launch depend on third-party CDNs: if any of them
// failed, `React` was undefined, the bundle's IIFE threw on its first line,
// and the user got a blank page. On iOS this was permanent, not intermittent -
// Capacitor serves from the capacitor:// scheme, where service workers don't
// run, so sw.js never cached them and every launch re-fetched from the network.
//
// Copying them out of node_modules makes the shipped app fully self-contained:
// same-origin, precached by the service worker, and honest about Guideline
// 2.5.2 (nothing is downloaded or executed at runtime).
//
// Each entry lists candidate paths because the exact file moves between major
// versions. A miss throws and fails the build - loudly and at deploy time,
// which is the correct place to find out. Never silently fall back to a CDN.
const vendor = [
  ["react.production.min.js",       ["node_modules/react/umd/react.production.min.js"]],
  ["react-dom.production.min.js",   ["node_modules/react-dom/umd/react-dom.production.min.js"]],
  ["firebase-app-compat.js",        ["node_modules/firebase/firebase-app-compat.js",
                                     "node_modules/firebase/compat/app/dist/index.umd.js"]],
  ["firebase-auth-compat.js",       ["node_modules/firebase/firebase-auth-compat.js",
                                     "node_modules/firebase/compat/auth/dist/index.umd.js"]],
  ["firebase-firestore-compat.js",  ["node_modules/firebase/firebase-firestore-compat.js",
                                     "node_modules/firebase/compat/firestore/dist/index.umd.js"]],
];

mkdirSync("public/vendor", { recursive: true });
for (const [name, candidates] of vendor) {
  const hit = candidates.find((p) => existsSync(p));
  if (!hit) {
    throw new Error(
      "Vendor asset not found: " + name + "\n" +
      "Looked in:\n  " + candidates.join("\n  ") + "\n" +
      "The package is probably installed at a different path in this version. " +
      "Add the correct path to the `vendor` list in build.mjs - do NOT go back " +
      "to loading it from a CDN (see the comment above)."
    );
  }
  copyFileSync(hit, "public/vendor/" + name);
}

// index.html and sw.js get the build id stamped in, so each deploy busts both
// the browser HTTP cache (?v=) and the service-worker cache (new cache name).
for (const f of ["index.html", "sw.js"]) {
  writeFileSync("public/" + f, readFileSync(f, "utf8").replace(/__RICHY_BUILD__/g, BUILD_ID));
}

console.log(
  "Built public/ (app.js " + Math.round(bundle.length / 1024) + " KB, " +
  vendor.length + " vendor files, build " + BUILD_ID + ")"
);
