import SwiftUI

/// The persistent AI identification shown wherever Richard speaks. It has to
/// be visible at or before the first interaction, and it names who generates
/// the replies - so it opens every conversation and is never an afterthought.
struct AIDisclosure: View {
    var body: some View {
        HStack(alignment: .top, spacing: Spacing.sm) {
            Image(systemName: "info.circle")
                .foregroundStyle(RichyColor.ink3)
            Text("Richard is an AI assistant. Replies are generated by Claude, a model made by Anthropic, from the numbers you keep in Richy, and can be wrong. Richard does not give investment advice. Long-press a reply to report it.")
                .font(RichyFont.ui(RichyFont.Size.footnote))
                .foregroundStyle(RichyColor.ink3)
        }
    }
}

#Preview("Disclosure") {
    AIDisclosure()
        .padding()
        .background(RichyColor.background)
}
