import SwiftUI

/// Stands in for Richard's chat. The AI identification line is here from day
/// one so it is never an afterthought: it must be visible at or before the
/// first interaction, and it names who generates the replies.
struct RichardPlaceholderView: View {
    var body: some View {
        NavigationStack {
            ZStack {
                RichyColor.background.ignoresSafeArea()
                VStack(spacing: Spacing.lg) {
                    EmptyStateView(icon: "bubble.left.and.text.bubble.right",
                                   title: "Richard is on his way",
                                   message: "Chat, the daily brief and the money leaks Richard spots arrive with the Richard feature.")
                    AIDisclosure()
                        .padding(.horizontal, Spacing.screen)
                        .padding(.bottom, Spacing.lg)
                }
            }
            .navigationTitle("Richard")
        }
    }
}

/// The persistent AI identification shown wherever Richard speaks.
struct AIDisclosure: View {
    var body: some View {
        HStack(alignment: .top, spacing: Spacing.sm) {
            Image(systemName: "info.circle")
                .foregroundStyle(RichyColor.ink3)
            Text("Richard is an AI assistant. Replies are generated by Claude, a model made by Anthropic, from the numbers you keep in Richy, and can be wrong. Richard does not give investment advice.")
                .font(RichyFont.ui(RichyFont.Size.footnote))
                .foregroundStyle(RichyColor.ink3)
        }
    }
}

#Preview("Richard placeholder") {
    RichardPlaceholderView()
}
